name: base-card

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.basecard.io/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/api.basecard.io/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - base-card

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - base-card
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  hardhat:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    networks:
      - base-card
    ports:
      - "8545:8545"

networks:
  base-card:
    driver: bridge