name: base-card

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - base-card
    ports:
      - "443:443"
    env_file:
      - ./backend/.env

  hardhat:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    networks:
      - base-card
    ports:
      - "8545:8545"

networks:
  base-card:
    driver: bridge